# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ninguem\Documents\estudos\projeto-ingles\tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1110, 800))
        MainWindow.setStyleSheet("alternate-background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1241, 171))
        self.frame.setStyleSheet(" background-color: rgb(240, 43, 209);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_67 = QtWidgets.QLabel(self.frame)
        self.label_67.setGeometry(QtCore.QRect(310, 40, 481, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(40)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("background-color: rgb(239, 201, 36);\n"
"border-radius:20px;")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.frame)
        self.label_68.setGeometry(QtCore.QRect(820, 0, 291, 251))
        self.label_68.setText("")
        self.label_68.setPixmap(QtGui.QPixmap("c:\\Users\\ninguem\\Documents\\estudos\\projeto-ingles\\imagens/alfabeto_2_250.png"))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.frame)
        self.label_69.setGeometry(QtCore.QRect(0, 0, 291, 251))
        self.label_69.setText("")
        self.label_69.setPixmap(QtGui.QPixmap("c:\\Users\\ninguem\\Documents\\estudos\\projeto-ingles\\imagens/alfabeto_2_250i2.png"))
        self.label_69.setObjectName("label_69")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(340, 270, 221, 80))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_105 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_105.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_105.setObjectName("horizontalLayout_105")
        self.caixa_letras_53 = QtWidgets.QFrame(self.horizontalLayoutWidget_9)
        self.caixa_letras_53.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_53.setObjectName("caixa_letras_53")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.caixa_letras_53)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_106 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_106.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_106.setObjectName("horizontalLayout_106")
        self.botao_i = QtWidgets.QPushButton(self.horizontalLayoutWidget_19)
        self.botao_i.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_i.setFont(font)
        self.botao_i.setStyleSheet("QPushButton#botao_i {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_i:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_i{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_i.setObjectName("botao_i")
        self.horizontalLayout_106.addWidget(self.botao_i)
        self.botao_j = QtWidgets.QPushButton(self.horizontalLayoutWidget_19)
        self.botao_j.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_j.setFont(font)
        self.botao_j.setStyleSheet("QPushButton#botao_j {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_j:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_j{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_j.setObjectName("botao_j")
        self.horizontalLayout_106.addWidget(self.botao_j)
        self.horizontalLayout_105.addWidget(self.caixa_letras_53)
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setGeometry(QtCore.QRect(620, 620, 221, 41))
        self.frame_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_114 = QtWidgets.QLabel(self.frame_13)
        self.label_114.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_114.setFont(font)
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.frame_13)
        self.label_115.setGeometry(QtCore.QRect(140, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_115.setFont(font)
        self.label_115.setObjectName("label_115")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(340, 370, 221, 31))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_116 = QtWidgets.QLabel(self.frame_7)
        self.label_116.setGeometry(QtCore.QRect(36, 3, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_116.setFont(font)
        self.label_116.setObjectName("label_116")
        self.label_117 = QtWidgets.QLabel(self.frame_7)
        self.label_117.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_117.setFont(font)
        self.label_117.setObjectName("label_117")
        self.horizontalLayoutWidget_29 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_29.setGeometry(QtCore.QRect(340, 660, 221, 80))
        self.horizontalLayoutWidget_29.setObjectName("horizontalLayoutWidget_29")
        self.horizontalLayout_107 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_29)
        self.horizontalLayout_107.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_107.setObjectName("horizontalLayout_107")
        self.caixa_letras_54 = QtWidgets.QFrame(self.horizontalLayoutWidget_29)
        self.caixa_letras_54.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_54.setObjectName("caixa_letras_54")
        self.horizontalLayoutWidget_41 = QtWidgets.QWidget(self.caixa_letras_54)
        self.horizontalLayoutWidget_41.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_41.setObjectName("horizontalLayoutWidget_41")
        self.horizontalLayout_108 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_41)
        self.horizontalLayout_108.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_108.setObjectName("horizontalLayout_108")
        self.botao_o = QtWidgets.QPushButton(self.horizontalLayoutWidget_41)
        self.botao_o.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_o.setFont(font)
        self.botao_o.setStyleSheet("QPushButton#botao_o {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_o:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_o{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_o.setObjectName("botao_o")
        self.horizontalLayout_108.addWidget(self.botao_o)
        self.botao_p = QtWidgets.QPushButton(self.horizontalLayoutWidget_41)
        self.botao_p.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_p.setFont(font)
        self.botao_p.setStyleSheet("QPushButton#botao_p {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_p:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_p{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_p.setObjectName("botao_p")
        self.horizontalLayout_108.addWidget(self.botao_p)
        self.horizontalLayout_107.addWidget(self.caixa_letras_54)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 270, 221, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_109 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_109.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_109.setObjectName("horizontalLayout_109")
        self.caixa_letras_55 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.caixa_letras_55.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_55.setObjectName("caixa_letras_55")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.caixa_letras_55)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_110 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_110.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_110.setObjectName("horizontalLayout_110")
        self.botao_a = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.botao_a.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_a.setFont(font)
        self.botao_a.setStyleSheet("QPushButton#botao_a {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_a:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_a{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_a.setObjectName("botao_a")
        self.horizontalLayout_110.addWidget(self.botao_a)
        self.botao_b = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.botao_b.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_b.setFont(font)
        self.botao_b.setStyleSheet("QPushButton#botao_b {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_b:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_b{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_b.setObjectName("botao_b")
        self.horizontalLayout_110.addWidget(self.botao_b)
        self.horizontalLayout_109.addWidget(self.caixa_letras_55)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(60, 630, 221, 31))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_118 = QtWidgets.QLabel(self.frame_5)
        self.label_118.setGeometry(QtCore.QRect(36, 3, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_118.setFont(font)
        self.label_118.setObjectName("label_118")
        self.label_119 = QtWidgets.QLabel(self.frame_5)
        self.label_119.setGeometry(QtCore.QRect(120, 3, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_119.setFont(font)
        self.label_119.setObjectName("label_119")
        self.horizontalLayoutWidget_49 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_49.setGeometry(QtCore.QRect(340, 400, 221, 80))
        self.horizontalLayoutWidget_49.setObjectName("horizontalLayoutWidget_49")
        self.horizontalLayout_111 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_49)
        self.horizontalLayout_111.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_111.setObjectName("horizontalLayout_111")
        self.caixa_letras_56 = QtWidgets.QFrame(self.horizontalLayoutWidget_49)
        self.caixa_letras_56.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_56.setObjectName("caixa_letras_56")
        self.horizontalLayoutWidget_54 = QtWidgets.QWidget(self.caixa_letras_56)
        self.horizontalLayoutWidget_54.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_54.setObjectName("horizontalLayoutWidget_54")
        self.horizontalLayout_112 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_54)
        self.horizontalLayout_112.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_112.setObjectName("horizontalLayout_112")
        self.botao_k = QtWidgets.QPushButton(self.horizontalLayoutWidget_54)
        self.botao_k.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_k.setFont(font)
        self.botao_k.setStyleSheet("QPushButton#botao_k {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_k:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_k{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_k.setObjectName("botao_k")
        self.horizontalLayout_112.addWidget(self.botao_k)
        self.botao_l = QtWidgets.QPushButton(self.horizontalLayoutWidget_54)
        self.botao_l.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_l.setFont(font)
        self.botao_l.setStyleSheet("QPushButton#botao_l {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_l:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_l{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_l.setObjectName("botao_l")
        self.horizontalLayout_112.addWidget(self.botao_l)
        self.horizontalLayout_111.addWidget(self.caixa_letras_56)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(60, 370, 221, 31))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_120 = QtWidgets.QLabel(self.frame_3)
        self.label_120.setGeometry(QtCore.QRect(50, 3, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_120.setFont(font)
        self.label_120.setObjectName("label_120")
        self.label_121 = QtWidgets.QLabel(self.frame_3)
        self.label_121.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_121.setFont(font)
        self.label_121.setObjectName("label_121")
        self.horizontalLayoutWidget_56 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_56.setGeometry(QtCore.QRect(60, 660, 221, 80))
        self.horizontalLayoutWidget_56.setObjectName("horizontalLayoutWidget_56")
        self.horizontalLayout_113 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_56)
        self.horizontalLayout_113.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_113.setObjectName("horizontalLayout_113")
        self.caixa_letras_57 = QtWidgets.QFrame(self.horizontalLayoutWidget_56)
        self.caixa_letras_57.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_57.setObjectName("caixa_letras_57")
        self.horizontalLayoutWidget_58 = QtWidgets.QWidget(self.caixa_letras_57)
        self.horizontalLayoutWidget_58.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_58.setObjectName("horizontalLayoutWidget_58")
        self.horizontalLayout_114 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_58)
        self.horizontalLayout_114.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_114.setObjectName("horizontalLayout_114")
        self.botao_g = QtWidgets.QPushButton(self.horizontalLayoutWidget_58)
        self.botao_g.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_g.setFont(font)
        self.botao_g.setStyleSheet("QPushButton#botao_g {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_g:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_g{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_g.setObjectName("botao_g")
        self.horizontalLayout_114.addWidget(self.botao_g)
        self.botao_h = QtWidgets.QPushButton(self.horizontalLayoutWidget_58)
        self.botao_h.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_h.setFont(font)
        self.botao_h.setStyleSheet("QPushButton#botao_h {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_h:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_h{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_h.setObjectName("botao_h")
        self.horizontalLayout_114.addWidget(self.botao_h)
        self.horizontalLayout_113.addWidget(self.caixa_letras_57)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(60, 240, 221, 31))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_122 = QtWidgets.QLabel(self.frame_2)
        self.label_122.setGeometry(QtCore.QRect(50, 3, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_122.setFont(font)
        self.label_122.setObjectName("label_122")
        self.label_123 = QtWidgets.QLabel(self.frame_2)
        self.label_123.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_123.setFont(font)
        self.label_123.setObjectName("label_123")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(880, 240, 221, 31))
        self.frame_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_124 = QtWidgets.QLabel(self.frame_14)
        self.label_124.setGeometry(QtCore.QRect(36, 3, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_124.setFont(font)
        self.label_124.setObjectName("label_124")
        self.label_125 = QtWidgets.QLabel(self.frame_14)
        self.label_125.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_125.setFont(font)
        self.label_125.setObjectName("label_125")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(340, 500, 221, 31))
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_126 = QtWidgets.QLabel(self.frame_8)
        self.label_126.setGeometry(QtCore.QRect(36, 3, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_126.setFont(font)
        self.label_126.setObjectName("label_126")
        self.label_127 = QtWidgets.QLabel(self.frame_8)
        self.label_127.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_127.setFont(font)
        self.label_127.setObjectName("label_127")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(340, 240, 221, 31))
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_128 = QtWidgets.QLabel(self.frame_6)
        self.label_128.setGeometry(QtCore.QRect(46, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_128.setFont(font)
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.frame_6)
        self.label_129.setGeometry(QtCore.QRect(140, 3, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_129.setFont(font)
        self.label_129.setObjectName("label_129")
        self.horizontalLayoutWidget_60 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_60.setGeometry(QtCore.QRect(60, 530, 221, 80))
        self.horizontalLayoutWidget_60.setObjectName("horizontalLayoutWidget_60")
        self.horizontalLayout_115 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_60)
        self.horizontalLayout_115.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_115.setObjectName("horizontalLayout_115")
        self.caixa_letras_58 = QtWidgets.QFrame(self.horizontalLayoutWidget_60)
        self.caixa_letras_58.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_58.setObjectName("caixa_letras_58")
        self.horizontalLayoutWidget_62 = QtWidgets.QWidget(self.caixa_letras_58)
        self.horizontalLayoutWidget_62.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_62.setObjectName("horizontalLayoutWidget_62")
        self.horizontalLayout_116 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_62)
        self.horizontalLayout_116.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_116.setObjectName("horizontalLayout_116")
        self.botao_e = QtWidgets.QPushButton(self.horizontalLayoutWidget_62)
        self.botao_e.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_e.setFont(font)
        self.botao_e.setStyleSheet("QPushButton#botao_e {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_e:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_e{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_e.setObjectName("botao_e")
        self.horizontalLayout_116.addWidget(self.botao_e)
        self.botao_f = QtWidgets.QPushButton(self.horizontalLayoutWidget_62)
        self.botao_f.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_f.setFont(font)
        self.botao_f.setStyleSheet("QPushButton#botao_f {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_f:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_f{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_f.setObjectName("botao_f")
        self.horizontalLayout_116.addWidget(self.botao_f)
        self.horizontalLayout_115.addWidget(self.caixa_letras_58)
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(620, 370, 221, 31))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_130 = QtWidgets.QLabel(self.frame_11)
        self.label_130.setGeometry(QtCore.QRect(46, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.label_131 = QtWidgets.QLabel(self.frame_11)
        self.label_131.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_131.setFont(font)
        self.label_131.setObjectName("label_131")
        self.horizontalLayoutWidget_64 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_64.setGeometry(QtCore.QRect(620, 270, 221, 80))
        self.horizontalLayoutWidget_64.setObjectName("horizontalLayoutWidget_64")
        self.horizontalLayout_117 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_64)
        self.horizontalLayout_117.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_117.setObjectName("horizontalLayout_117")
        self.caixa_letras_59 = QtWidgets.QFrame(self.horizontalLayoutWidget_64)
        self.caixa_letras_59.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_59.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_59.setObjectName("caixa_letras_59")
        self.horizontalLayoutWidget_66 = QtWidgets.QWidget(self.caixa_letras_59)
        self.horizontalLayoutWidget_66.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_66.setObjectName("horizontalLayoutWidget_66")
        self.horizontalLayout_118 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_66)
        self.horizontalLayout_118.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_118.setObjectName("horizontalLayout_118")
        self.botao_q = QtWidgets.QPushButton(self.horizontalLayoutWidget_66)
        self.botao_q.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_q.setFont(font)
        self.botao_q.setStyleSheet("QPushButton#botao_q {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_q:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_q{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_q.setObjectName("botao_q")
        self.horizontalLayout_118.addWidget(self.botao_q)
        self.botao_r = QtWidgets.QPushButton(self.horizontalLayoutWidget_66)
        self.botao_r.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_r.setFont(font)
        self.botao_r.setStyleSheet("QPushButton#botao_r {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_r:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_r{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_r.setObjectName("botao_r")
        self.horizontalLayout_118.addWidget(self.botao_r)
        self.horizontalLayout_117.addWidget(self.caixa_letras_59)
        self.horizontalLayoutWidget_67 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_67.setGeometry(QtCore.QRect(60, 400, 221, 80))
        self.horizontalLayoutWidget_67.setObjectName("horizontalLayoutWidget_67")
        self.horizontalLayout_119 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_67)
        self.horizontalLayout_119.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_119.setObjectName("horizontalLayout_119")
        self.caixa_letras_60 = QtWidgets.QFrame(self.horizontalLayoutWidget_67)
        self.caixa_letras_60.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_60.setObjectName("caixa_letras_60")
        self.horizontalLayoutWidget_68 = QtWidgets.QWidget(self.caixa_letras_60)
        self.horizontalLayoutWidget_68.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_68.setObjectName("horizontalLayoutWidget_68")
        self.horizontalLayout_120 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_68)
        self.horizontalLayout_120.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_120.setObjectName("horizontalLayout_120")
        self.botao_c = QtWidgets.QPushButton(self.horizontalLayoutWidget_68)
        self.botao_c.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_c.setFont(font)
        self.botao_c.setStyleSheet("QPushButton#botao_c {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_c:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_c{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_c.setObjectName("botao_c")
        self.horizontalLayout_120.addWidget(self.botao_c)
        self.botao_d = QtWidgets.QPushButton(self.horizontalLayoutWidget_68)
        self.botao_d.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_d.setFont(font)
        self.botao_d.setStyleSheet("QPushButton#botao_d {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_d:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_d{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_d.setObjectName("botao_d")
        self.horizontalLayout_120.addWidget(self.botao_d)
        self.horizontalLayout_119.addWidget(self.caixa_letras_60)
        self.horizontalLayoutWidget_69 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_69.setGeometry(QtCore.QRect(340, 530, 221, 80))
        self.horizontalLayoutWidget_69.setObjectName("horizontalLayoutWidget_69")
        self.horizontalLayout_121 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_69)
        self.horizontalLayout_121.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_121.setObjectName("horizontalLayout_121")
        self.caixa_letras_61 = QtWidgets.QFrame(self.horizontalLayoutWidget_69)
        self.caixa_letras_61.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_61.setObjectName("caixa_letras_61")
        self.horizontalLayoutWidget_70 = QtWidgets.QWidget(self.caixa_letras_61)
        self.horizontalLayoutWidget_70.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_70.setObjectName("horizontalLayoutWidget_70")
        self.horizontalLayout_122 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_70)
        self.horizontalLayout_122.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_122.setObjectName("horizontalLayout_122")
        self.botao_m = QtWidgets.QPushButton(self.horizontalLayoutWidget_70)
        self.botao_m.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_m.setFont(font)
        self.botao_m.setStyleSheet("QPushButton#botao_m {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_m:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_m{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_m.setObjectName("botao_m")
        self.horizontalLayout_122.addWidget(self.botao_m)
        self.botao_n = QtWidgets.QPushButton(self.horizontalLayoutWidget_70)
        self.botao_n.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_n.setFont(font)
        self.botao_n.setStyleSheet("QPushButton#botao_n {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_n:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_n{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_n.setObjectName("botao_n")
        self.horizontalLayout_122.addWidget(self.botao_n)
        self.horizontalLayout_121.addWidget(self.caixa_letras_61)
        self.horizontalLayoutWidget_71 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_71.setGeometry(QtCore.QRect(620, 660, 221, 80))
        self.horizontalLayoutWidget_71.setObjectName("horizontalLayoutWidget_71")
        self.horizontalLayout_123 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_71)
        self.horizontalLayout_123.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_123.setObjectName("horizontalLayout_123")
        self.caixa_letras_62 = QtWidgets.QFrame(self.horizontalLayoutWidget_71)
        self.caixa_letras_62.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_62.setObjectName("caixa_letras_62")
        self.horizontalLayoutWidget_72 = QtWidgets.QWidget(self.caixa_letras_62)
        self.horizontalLayoutWidget_72.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_72.setObjectName("horizontalLayoutWidget_72")
        self.horizontalLayout_124 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_72)
        self.horizontalLayout_124.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_124.setObjectName("horizontalLayout_124")
        self.botao_w = QtWidgets.QPushButton(self.horizontalLayoutWidget_72)
        self.botao_w.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_w.setFont(font)
        self.botao_w.setStyleSheet("QPushButton#botao_w {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_w:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_w{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_w.setObjectName("botao_w")
        self.horizontalLayout_124.addWidget(self.botao_w)
        self.botao_x = QtWidgets.QPushButton(self.horizontalLayoutWidget_72)
        self.botao_x.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_x.setFont(font)
        self.botao_x.setStyleSheet("QPushButton#botao_x {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_x:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_x{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_x.setObjectName("botao_x")
        self.horizontalLayout_124.addWidget(self.botao_x)
        self.horizontalLayout_123.addWidget(self.caixa_letras_62)
        self.horizontalLayoutWidget_73 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_73.setGeometry(QtCore.QRect(880, 270, 221, 80))
        self.horizontalLayoutWidget_73.setObjectName("horizontalLayoutWidget_73")
        self.horizontalLayout_125 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_73)
        self.horizontalLayout_125.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_125.setObjectName("horizontalLayout_125")
        self.caixa_letras_63 = QtWidgets.QFrame(self.horizontalLayoutWidget_73)
        self.caixa_letras_63.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_63.setObjectName("caixa_letras_63")
        self.horizontalLayoutWidget_74 = QtWidgets.QWidget(self.caixa_letras_63)
        self.horizontalLayoutWidget_74.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_74.setObjectName("horizontalLayoutWidget_74")
        self.horizontalLayout_126 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_74)
        self.horizontalLayout_126.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_126.setObjectName("horizontalLayout_126")
        self.botao_y = QtWidgets.QPushButton(self.horizontalLayoutWidget_74)
        self.botao_y.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_y.setFont(font)
        self.botao_y.setStyleSheet("QPushButton#botao_y {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_y:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_y{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_y.setObjectName("botao_y")
        self.horizontalLayout_126.addWidget(self.botao_y)
        self.botao_z = QtWidgets.QPushButton(self.horizontalLayoutWidget_74)
        self.botao_z.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_z.setFont(font)
        self.botao_z.setStyleSheet("QPushButton#botao_z {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_z:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_z{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_z.setObjectName("botao_z")
        self.horizontalLayout_126.addWidget(self.botao_z)
        self.horizontalLayout_125.addWidget(self.caixa_letras_63)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(300, 240, 21, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setGeometry(QtCore.QRect(620, 500, 221, 31))
        self.frame_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_132 = QtWidgets.QLabel(self.frame_12)
        self.label_132.setGeometry(QtCore.QRect(46, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_132.setFont(font)
        self.label_132.setObjectName("label_132")
        self.label_133 = QtWidgets.QLabel(self.frame_12)
        self.label_133.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_133.setFont(font)
        self.label_133.setObjectName("label_133")
        self.horizontalLayoutWidget_75 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_75.setGeometry(QtCore.QRect(620, 400, 221, 80))
        self.horizontalLayoutWidget_75.setObjectName("horizontalLayoutWidget_75")
        self.horizontalLayout_127 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_75)
        self.horizontalLayout_127.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_127.setObjectName("horizontalLayout_127")
        self.caixa_letras_64 = QtWidgets.QFrame(self.horizontalLayoutWidget_75)
        self.caixa_letras_64.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_64.setObjectName("caixa_letras_64")
        self.horizontalLayoutWidget_76 = QtWidgets.QWidget(self.caixa_letras_64)
        self.horizontalLayoutWidget_76.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_76.setObjectName("horizontalLayoutWidget_76")
        self.horizontalLayout_128 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_76)
        self.horizontalLayout_128.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_128.setObjectName("horizontalLayout_128")
        self.botao_s = QtWidgets.QPushButton(self.horizontalLayoutWidget_76)
        self.botao_s.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_s.setFont(font)
        self.botao_s.setStyleSheet("QPushButton#botao_s {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_s:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_s{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_s.setObjectName("botao_s")
        self.horizontalLayout_128.addWidget(self.botao_s)
        self.botao_t = QtWidgets.QPushButton(self.horizontalLayoutWidget_76)
        self.botao_t.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_t.setFont(font)
        self.botao_t.setStyleSheet("QPushButton#botao_t {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_t:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_t{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_t.setObjectName("botao_t")
        self.horizontalLayout_128.addWidget(self.botao_t)
        self.horizontalLayout_127.addWidget(self.caixa_letras_64)
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(620, 240, 221, 31))
        self.frame_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_134 = QtWidgets.QLabel(self.frame_10)
        self.label_134.setGeometry(QtCore.QRect(26, 3, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_134.setFont(font)
        self.label_134.setObjectName("label_134")
        self.label_135 = QtWidgets.QLabel(self.frame_10)
        self.label_135.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_135.setFont(font)
        self.label_135.setObjectName("label_135")
        self.horizontalLayoutWidget_77 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_77.setGeometry(QtCore.QRect(620, 530, 221, 80))
        self.horizontalLayoutWidget_77.setObjectName("horizontalLayoutWidget_77")
        self.horizontalLayout_129 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_77)
        self.horizontalLayout_129.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_129.setObjectName("horizontalLayout_129")
        self.caixa_letras_65 = QtWidgets.QFrame(self.horizontalLayoutWidget_77)
        self.caixa_letras_65.setStyleSheet("background-color: rgb(239, 201, 36);")
        self.caixa_letras_65.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caixa_letras_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caixa_letras_65.setObjectName("caixa_letras_65")
        self.horizontalLayoutWidget_78 = QtWidgets.QWidget(self.caixa_letras_65)
        self.horizontalLayoutWidget_78.setGeometry(QtCore.QRect(0, -1, 221, 81))
        self.horizontalLayoutWidget_78.setObjectName("horizontalLayoutWidget_78")
        self.horizontalLayout_130 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_78)
        self.horizontalLayout_130.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_130.setObjectName("horizontalLayout_130")
        self.botao_u = QtWidgets.QPushButton(self.horizontalLayoutWidget_78)
        self.botao_u.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_u.setFont(font)
        self.botao_u.setStyleSheet("QPushButton#botao_u {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_u:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_u{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_u.setObjectName("botao_u")
        self.horizontalLayout_130.addWidget(self.botao_u)
        self.botao_v = QtWidgets.QPushButton(self.horizontalLayoutWidget_78)
        self.botao_v.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.botao_v.setFont(font)
        self.botao_v.setStyleSheet("QPushButton#botao_v {\n"
"    background-color: rgb(240, 43, 209);  /*roxo: rgb(240, 43, 209);*/\n"
"}\n"
"\n"
"QPushButton#botao_v:pressed {\n"
"   background-color: rgb(170, 0, 255)  /* Cor de fundo quando o botão é pressionado */\n"
"}\n"
"\n"
"QPushButton#botao_v{\n"
"    border-radius: 10px;\n"
"}")
        self.botao_v.setObjectName("botao_v")
        self.horizontalLayout_130.addWidget(self.botao_v)
        self.horizontalLayout_129.addWidget(self.caixa_letras_65)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(850, 240, 21, 501))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(580, 240, 21, 501))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(60, 490, 221, 41))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_136 = QtWidgets.QLabel(self.frame_4)
        self.label_136.setGeometry(QtCore.QRect(50, 10, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_136.setFont(font)
        self.label_136.setObjectName("label_136")
        self.label_137 = QtWidgets.QLabel(self.frame_4)
        self.label_137.setGeometry(QtCore.QRect(160, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_137.setFont(font)
        self.label_137.setObjectName("label_137")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(340, 630, 221, 31))
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_138 = QtWidgets.QLabel(self.frame_9)
        self.label_138.setGeometry(QtCore.QRect(36, 3, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_138.setFont(font)
        self.label_138.setObjectName("label_138")
        self.label_139 = QtWidgets.QLabel(self.frame_9)
        self.label_139.setGeometry(QtCore.QRect(150, 3, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_139.setFont(font)
        self.label_139.setObjectName("label_139")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_67.setText(_translate("MainWindow", "  Alphabet English  "))
        self.botao_i.setText(_translate("MainWindow", "I"))
        self.botao_j.setText(_translate("MainWindow", "J"))
        self.label_114.setText(_translate("MainWindow", "DÃBLIU"))
        self.label_115.setText(_translate("MainWindow", "ÉCS"))
        self.label_116.setText(_translate("MainWindow", "KEI"))
        self.label_117.setText(_translate("MainWindow", "EL"))
        self.botao_o.setText(_translate("MainWindow", "O"))
        self.botao_p.setText(_translate("MainWindow", "P"))
        self.botao_a.setText(_translate("MainWindow", "A"))
        self.botao_b.setText(_translate("MainWindow", "B"))
        self.label_118.setText(_translate("MainWindow", "DJI"))
        self.label_119.setText(_translate("MainWindow", " EITCH"))
        self.botao_k.setText(_translate("MainWindow", "K"))
        self.botao_l.setText(_translate("MainWindow", "L"))
        self.label_120.setText(_translate("MainWindow", "CI"))
        self.label_121.setText(_translate("MainWindow", "DI"))
        self.botao_g.setText(_translate("MainWindow", "G"))
        self.botao_h.setText(_translate("MainWindow", "H"))
        self.label_122.setText(_translate("MainWindow", "EI"))
        self.label_123.setText(_translate("MainWindow", "BI"))
        self.label_124.setText(_translate("MainWindow", "UAI"))
        self.label_125.setText(_translate("MainWindow", "ZI"))
        self.label_126.setText(_translate("MainWindow", "EM"))
        self.label_127.setText(_translate("MainWindow", "EN"))
        self.label_128.setText(_translate("MainWindow", "AI"))
        self.label_129.setText(_translate("MainWindow", "DJEI"))
        self.botao_e.setText(_translate("MainWindow", "E"))
        self.botao_f.setText(_translate("MainWindow", "F"))
        self.label_130.setText(_translate("MainWindow", "ES"))
        self.label_131.setText(_translate("MainWindow", "TI"))
        self.botao_q.setText(_translate("MainWindow", "Q"))
        self.botao_r.setText(_translate("MainWindow", "R"))
        self.botao_c.setText(_translate("MainWindow", "C"))
        self.botao_d.setText(_translate("MainWindow", "D"))
        self.botao_m.setText(_translate("MainWindow", "M"))
        self.botao_n.setText(_translate("MainWindow", "N"))
        self.botao_w.setText(_translate("MainWindow", "W"))
        self.botao_x.setText(_translate("MainWindow", "X"))
        self.botao_y.setText(_translate("MainWindow", "Y"))
        self.botao_z.setText(_translate("MainWindow", "Z"))
        self.label_132.setText(_translate("MainWindow", "IU"))
        self.label_133.setText(_translate("MainWindow", "VI"))
        self.botao_s.setText(_translate("MainWindow", "S"))
        self.botao_t.setText(_translate("MainWindow", "T"))
        self.label_134.setText(_translate("MainWindow", "QUIU"))
        self.label_135.setText(_translate("MainWindow", "AR"))
        self.botao_u.setText(_translate("MainWindow", "U"))
        self.botao_v.setText(_translate("MainWindow", "V"))
        self.label_136.setText(_translate("MainWindow", "I"))
        self.label_137.setText(_translate("MainWindow", "ÉF"))
        self.label_138.setText(_translate("MainWindow", "OU"))
        self.label_139.setText(_translate("MainWindow", "PI"))
